<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Version>1.0.0</Version>
        <Description>Useful TOR Stuff - Bloody-modifier lag throttle and a permanent client-side Snitch reveal fix</Description>
        <Authors>DaUnknown-0</Authors>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <Platforms>AnyCPU</Platforms>
        <AssemblyName>UsefulTORStuff</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AmongUs.GameLibs.Steam" Version="2024.10.29" />
        <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" />
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.697" />
    </ItemGroup>

    <Target Name="CopyCustomContent" AfterTargets="AfterBuild" Condition="Exists('$(AmongUsLatest)/BepInEx/plugins/')">
        <Message Text="Copying UsefulTORStuff to BepInEx plugins" />
        <Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\net6.0\UsefulTORStuff.dll" DestinationFolder="$(AmongUsLatest)/BepInEx/plugins/" />
    </Target>
</Project>
