// Useful TOR Stuff - Copyright (C) 2026 DaUnknown-0
// Licensed under GPL-3.0-or-later. See LICENSE for details.
// Based on The Other Roles (https://github.com/TheOtherRolesAU/TheOtherRoles), GPL-3.0.

/*
 * UTSAssets - own button icons + sound cues for the Useful TOR Stuff features.
 *
 * Icons are embedded PNGs drawn in the TOR comic-burst style (generated by the shared AssetGen tool
 * in "TOR Mod\Assets"); this brings its own sprite loader because TOR's Helpers.loadSpriteFromResources
 * only reads TOR's assembly. Sounds are headerless 2-channel signed 32-bit PCM LE @ 48 kHz (the same
 * format the TOR/UC raw loaders use). Resources use explicit LogicalNames "UsefulTORStuff.Resources.*"
 * (see the .csproj) so the lookup never depends on the root-namespace default.
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEngine;

namespace UsefulTORStuff {
    public static class UTSAssets {
        private static readonly Dictionary<string, Sprite> sprites = new();
        private static readonly Dictionary<string, AudioClip> clips = new();

        public static Sprite UnshieldIcon => GetSprite("UsefulTORStuff.Resources.uts_unshield.png", 115f);
        public static Sprite SelfLimpIcon => GetSprite("UsefulTORStuff.Resources.uts_selflimp.png", 115f);
        public static Sprite MixupIcon => GetSprite("UsefulTORStuff.Resources.uts_mixup.png", 115f);
        public static Sprite BombCancelIcon => GetSprite("UsefulTORStuff.Resources.uts_bombcancel.png", 115f);
        public static Sprite RevengerIcon => GetSprite("UsefulTORStuff.Resources.uts_revenger.png", 115f);

        public static void PlayReshield(float volume = 0.7f) => Play("uts_reshield", volume);
        public static void PlayLimpToggle(float volume = 0.6f) => Play("uts_limp", volume);
        public static void PlayMixup(float volume = 0.8f) => Play("uts_mixup", volume);
        public static void PlayBombCancel(float volume = 0.7f) => Play("uts_bombcancel", volume);
        public static void PlayRevenger(float volume = 0.85f) => Play("uts_revenger", volume);

        private static Sprite GetSprite(string path, float pixelsPerUnit) {
            string key = path + "_" + pixelsPerUnit;
            if (sprites.TryGetValue(key, out var cached) && cached != null) return cached;
            try {
                var asm = Assembly.GetExecutingAssembly();
                using Stream stream = asm.GetManifestResourceStream(path);
                if (stream == null) return null;
                var data = new byte[stream.Length];
                _ = stream.Read(data, 0, (int)stream.Length);
                var tex = new Texture2D(2, 2, TextureFormat.ARGB32, true);
                if (!ImageConversion.LoadImage(tex, data, false)) return null;
                tex.hideFlags |= HideFlags.HideAndDontSave | HideFlags.DontSaveInEditor;
                var sprite = Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height),
                    new Vector2(0.5f, 0.5f), pixelsPerUnit);
                sprite.hideFlags |= HideFlags.HideAndDontSave | HideFlags.DontSaveInEditor;
                sprites[key] = sprite;
                return sprite;
            } catch (Exception e) {
                UsefulTORStuffPlugin.Logger?.LogWarning($"[UTSAssets] sprite load failed ({path}): {e.Message}");
                return null;
            }
        }

        private static void Play(string name, float volume) {
            try {
                var clip = GetClip(name);
                if (clip == null || SoundManager.Instance == null) return;
                SoundManager.Instance.PlaySound(clip, false, volume);
            } catch (Exception e) {
                UsefulTORStuffPlugin.Logger?.LogWarning($"[UTSAssets] Play {name} failed: {e.Message}");
            }
        }

        private static AudioClip GetClip(string name) {
            if (clips.TryGetValue(name, out var cached) && cached != null) return cached;
            var clip = LoadRawClip($"UsefulTORStuff.Resources.{name}.raw", name);
            clips[name] = clip;
            return clip;
        }

        // Raw (headerless) 2-channel signed 32-bit PCM (LE), 48 kHz.
        private static AudioClip LoadRawClip(string path, string clipName) {
            try {
                Assembly assembly = Assembly.GetExecutingAssembly();
                using Stream stream = assembly.GetManifestResourceStream(path);
                if (stream == null) return null;
                var bytes = new byte[stream.Length];
                _ = stream.Read(bytes, 0, (int)stream.Length);
                float[] samples = new float[bytes.Length / 4];
                for (int i = 0; i < samples.Length; i++)
                    samples[i] = (float)BitConverter.ToInt32(bytes, i * 4) / int.MaxValue;
                AudioClip clip = AudioClip.Create(clipName, samples.Length / 2, 2, 48000, false);
                clip.hideFlags |= HideFlags.HideAndDontSave | HideFlags.DontSaveInEditor;
                clip.SetData(samples, 0);
                return clip;
            } catch {
                return null;
            }
        }
    }
}
